### ISSUE TITLE
Can you look at caching certain results?

### ISSUE THREAD

**Issue by chrzrdx** [bhagyesh96/redis-jobs#10]
https://github.com/bhagyesh96/flask-sample/blob/1909135ed7bbec0871c0c9886fb2b6417c854309/flaskr/app.py#L37

eg: If I submit a thousand jobs for counting words at google.com, don't make 1000 requests, since data may not have changed in the short time it takes to make those requests. Instead, try to cache the response and see if you can respond with that.

**Comment by bhagyesh96** [comment]
Yes in flask by flask cache.
Eg. 

from flask_cache import Cache

cache = Cache(app, config={'CACHE_TYPE': 'redis'})

@cache.memoize(timeout=60)
def query_db():
    time.sleep(5)
    return "Results from DB"


Will update code ASAP

**Comment by bhagyesh96** [comment]
Yes in flask by flask cache.
Eg. 
cache = Cache(app, config={'CACHE_TYPE': 'redis'})

@cache.memoize(timeout=60)
def query_db():
    time.sleep(5)
    return "Results from DB"

**Comment by bhagyesh96** [comment]
done implemented look code

**Comment by bhagyesh96** [comment]
NOTE : Some backend implementations do not support completely clearing the cache. Also, if you’re not using a key prefix, some implementations (e.g. Redis) will flush the whole database. Make sure you’re not storing any other data in your caching database.
