### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by chrzrdx** [bhagyesh96/redis-jobs#12]
Provide a docker-compose.yml that starts up:

a) the web server
b) redis
c) any database you may be using
d) workers for the web server

This will greatly simplify the instructions to setup and start the project

**Comment by bhagyesh96** [comment]
prior experience of working on ec2, ebs and heroku.
will do it ASAP

**Comment by bhagyesh96** [comment]
Application Dockerised

**Comment by bhagyesh96** [comment]
Application Dockerised
