### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by chrzrdx** [bhagyesh96/redis-jobs#5]
Organise all imports at the top
https://github.com/bhagyesh96/flask-sample/blob/1909135ed7bbec0871c0c9886fb2b6417c854309/flaskr/app.py#L23

You can format your code using the `black` formatter, and run `autopep8` to make it PEP8 compliant.

**Comment by bhagyesh96** [comment]
this is my first flask app previously i worked in Django.

**Comment by bhagyesh96** [comment]
i will change the structure

**Comment by bhagyesh96** [comment]
count_word will have no access to db then because import will not receive db parameter
