### ISSUE TITLE
Remove dependency on nltk, use a simple regex to break into words

### ISSUE THREAD

**Issue by chrzrdx** [bhagyesh96/redis-jobs#7]
https://github.com/bhagyesh96/flask-sample/blob/1909135ed7bbec0871c0c9886fb2b6417c854309/flaskr/count_word.py#L15

You can forgo using a library for this, every space separated token in the response may be considered a word - bonus points if you can strip the html tags using a simple regex before counting space separated words.

**Comment by bhagyesh96** [comment]
nltk dependency removed

**Comment by bhagyesh96** [comment]
implemented with regex
